{{- if .Values.nacos.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-pvc
  labels:
    app: nacos
    {{- include "middleware.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.nacos.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  labels:
    app: nacos
    {{- include "middleware.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: nacos
  replicas: 1
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: {{ .Values.nacos.image }}
          env:
            - name: MODE
              value: standalone
            - name: PREFER_HOST_MODE
              value: hostname
            - name: NACOS_AUTH_ENABLE
              value: "false"
            - name: NACOS_AUTH_TOKEN
              value: {{ .Values.nacos.authToken | quote }}
            - name: NACOS_AUTH_IDENTITY_KEY
              value: {{ .Values.nacos.identityKey | quote }}
            - name: NACOS_AUTH_IDENTITY_VALUE
              value: {{ .Values.nacos.identityValue | quote }}
          ports:
            - containerPort: 8848
            - containerPort: 9848
          readinessProbe:
            tcpSocket:
              port: 8848
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          volumeMounts:
            - name: data
              mountPath: /home/nacos/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nacos-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  labels:
    app: nacos
    {{- include "middleware.labels" . | nindent 4 }}
spec:
  selector:
    app: nacos
  ports:
    - name: http
      port: 8848
    - name: grpc
      port: 9848
{{- end }}
