{{- if .Values.scylladb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scylladb
  labels:
    app: scylladb
    {{- include "middleware.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: scylladb
  serviceName: scylladb
  replicas: 1
  template:
    metadata:
      labels:
        app: scylladb
    spec:
      containers:
        - name: scylladb
          image: {{ .Values.scylladb.image }}
          args: ["--smp", {{ .Values.scylladb.smp | quote }}, "--memory", {{ .Values.scylladb.memory | quote }}, "--overprovisioned", "1"]
          ports:
            - containerPort: 9042
              name: cql
          volumeMounts:
            - name: data
              mountPath: /var/lib/scylla
          readinessProbe:
            exec:
              command: ["cqlsh", "-e", "describe keyspaces"]
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: {{ .Values.scylladb.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: scylladb
  labels:
    app: scylladb
    {{- include "middleware.labels" . | nindent 4 }}
spec:
  selector:
    app: scylladb
  ports:
    - port: 9042
      name: cql
{{- end }}
