apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
spec:
  selector:
    matchLabels:
      app: nacos
  replicas: 1
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: nacos/nacos-server:v2.3.0
          env:
            - name: MODE
              value: standalone
            - name: PREFER_HOST_MODE
              value: hostname
          ports:
            - containerPort: 8848
            - containerPort: 9848
          readinessProbe:
            httpGet:
              path: /nacos/v1/console/health/readiness
              port: 8848
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          volumeMounts:
            - name: data
              mountPath: /home/nacos/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nacos-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
spec:
  selector:
    app: nacos
  ports:
    - name: http
      port: 8848
    - name: grpc
      port: 9848
