apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
spec:
  selector:
    matchLabels:
      app: nacos
  replicas: 1
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: nacos/nacos-server:v3.1.1-slim
          env:
            - name: MODE
              value: standalone
            - name: PREFER_HOST_MODE
              value: hostname
            - name: NACOS_AUTH_ENABLE
              value: "false"
            - name: NACOS_AUTH_TOKEN
              value: "U2VjcmV0S2V5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5"
            - name: NACOS_AUTH_IDENTITY_KEY
              value: nacosDevIdentityKey2026
            - name: NACOS_AUTH_IDENTITY_VALUE
              value: nacosDevSecretValue888
          ports:
            - containerPort: 8848
            - containerPort: 9848
          readinessProbe:
            tcpSocket:
              port: 8848
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          volumeMounts:
            - name: data
              mountPath: /home/nacos/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nacos-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
spec:
  selector:
    app: nacos
  ports:
    - name: http
      port: 8848
    - name: grpc
      port: 9848
